### ISSUE TITLE
Game Won't Play

### ISSUE THREAD

**Issue by aschoppet** [DarthStrom/BlackBox#7]
I got the Black Box for my iPad, but when I try to play, nothing happens. I've touched every square around the outside edge, but I get nothing. Please help.

**Comment by DarthStrom** [comment]
I noticed as well - something seems to have changed with the way spritekit finds nodes based on touch location.  It still works on iOS 8 but is broken in 9.  I will work on tracking down exactly what is happening and submit a fix as soon as I can.

**Comment by aschoppet** [comment]
Thank you!

**Comment by DarthStrom** [comment]
I submitted a fix to the app store, you should get an update once it's approved.

**Comment by aschoppet** [comment]
Great news, Jason!  I look forward to playing it.

Alan

**Comment by DarthStrom** [comment]
New version is now available in the app store and should fix the issue.

**Comment by aschoppet** [comment]
It works great. If you plan to make any adjustments, consider telling the player how many balls to look for. There was one game where I found the 4 balls, but it would not show the finish button. I had hit every button on the edge, not realizing that there were 5 balls in play. Otherwise, I love the game!

Thanks,
Alan

**Comment by DarthStrom** [comment]
Glad to hear it works for you and that you're enjoying it.  I considered displaying how many balls were left but settled on hiding the finish button as an indication that guessing isn't done yet.  I'll probably add the number of balls somewhere as well based on your suggestion.  Thanks for the feedback!

-Jason
