### ISSUE TITLE
Hit/Reflection

### ISSUE THREAD

**Issue by aschoppet** [DarthStrom/BlackBox#8]
While playing a game, there were 2 balls next to each other and right on the edge. I got 3 reflections, when I think that 2 of them should have been Hits. Since the rules have the Hit 1st, they should take priority over a Reflection.

**Comment by DarthStrom** [comment]
Ok, I'll look into that.  Thanks for the feedback.

**Comment by DarthStrom** [comment]
Another update should be on its way that fixes this issue.  I also added an indicator for how many balls are hidden based on your suggestion in #7

**Comment by aschoppet** [comment]
Nice! I look forward to playing the update.

Another suggestion, that is NOT a problem. Along with the info in the upper right hand corner, you could add a running total of games & scores for every time the app is open.

Thanks,
Alan

**Comment by DarthStrom** [comment]
New version is available for download in the app store.

**Comment by aschoppet** [comment]
Thanks!
